### ISSUE TITLE
Problem sign apk

### ISSUE THREAD

**Issue by Jeiel0rbit** [Aefyr/SAI#257] opened 2022-07-23 13:50 UTC
The app does not sign apk when the function is enabled. This happens on my Android 11.

**Comment by Hypernovic** [comment] 2022-08-28 22:31
This Owner of this repository actually discontinued supporting this app according to the readme file,

Anyways that signing issue is caused by jarsigner used here, 
it can be resolved by using apksigner as it adheres to the V2 standard,
Unfortunately android 11 and above only uses this V2 standard.

The problem is you also cant sign a bundle using apksigner.

**Closed as completed** 2022-08-28 23:38 UTC
